[package]
name = "renderer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0"
ash = "0.32.1"
ash-window = "0.6.0"
raw-window-handle = "0.3.3"